{
 "openapi": "3.1.0",
 "info": {
  "title": "OWJ CRS Flight Microservice",
  "description": "This is the API documentation for the OWJ CRS Flight Service.",
  "version": "1.0.0"
 },
 "servers": [
  {
   "url": "https://flight.owj.app/",
   "description": "Production environment"
  },
  {
   "url": "http://localhost:8000/",
   "description": "Local environment"
  }
 ],
 "paths": {
  "/api/flight/v1/search": {
   "post": {
    "tags": [
     "Flight Search"
    ],
    "summary": "Create Flight Search",
    "description": "This Method is for flight search.\nIt provides search id for the search request which can be used to get the results.\nIt also provides any flights that are available at the time of the request",
    "operationId": "search"
   }
  },
  "/api/flight/v1/searchtest": {
   "post": {
    "tags": [
     "Flight Search"
    ],
    "summary": "Create Flight Search 2",
    "description": "This Method is for flight search.\nIt provides search id for the search request which can be used to get the results.\nIt also provides any flights that are available at the time of the request",
    "operationId": "search_2"
   }
  },
  "/api/flight/v1/search/{searchId}": {
   "get": {
    "tags": [
     "Flight Search"
    ],
    "summary": "Get Flight Search",
    "description": "This Method is for getting the results of a search.\nIt provides the results of the search with the given search id.",
    "operationId": "rch"
   }
  },
  "/api/flight/v1/validate": {
   "post": {
    "tags": [
     "Flight Validate"
    ],
    "summary": "Validate Flight",
    "operationId": ""
   }
  },
  "/api/flight/v1/book": {
   "post": {
    "tags": [
     "Flight Book"
    ],
    "summary": "Book",
    "operationId": ""
   }
  },
  "/api/flight/v1/grid": {
   "post": {
    "tags": [
     "Flight Grid"
    ],
    "summary": "Grid Search",
    "description": "This Method is for grid search.\nIt provides the cheapest price for each day between the given dates.",
    "operationId": ""
   }
  },
  "/api/flight/v1/apis": {
   "post": {
    "tags": [
     "Flight APIs"
    ],
    "summary": "Create Flight Api",
    "description": "This Method is for creating a flight api.",
    "operationId": "t_api"
   },
   "get": {
    "tags": [
     "Flight APIs"
    ],
    "summary": "List Flight Apis",
    "operationId": "apis"
   }
  },
  "/api/flight/v1/apis/{uuid}": {
   "get": {
    "tags": [
     "Flight APIs"
    ],
    "summary": "Get Flight Api",
    "operationId": "pi"
   },
   "put": {
    "tags": [
     "Flight APIs"
    ],
    "summary": "Update Flight Api",
    "operationId": "t_api"
   },
   "delete": {
    "tags": [
     "Flight APIs"
    ],
    "summary": "Delete Flight Api",
    "operationId": "t_api"
   }
  },
  "/api/flight/v1/airline": {
   "post": {
    "tags": [
     "Airline"
    ],
    "summary": "Create Airline",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: AIRLINE:CREATE",
    "operationId": "irline",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "AIRLINE:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Airline"
    ],
    "summary": "List Airlines",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: AIRLINE:READ",
    "operationId": "lines",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "AIRLINE:READ"
      ]
     }
    ]
   }
  },
  "/api/flight/v1/airline/{id}": {
   "get": {
    "tags": [
     "Airline"
    ],
    "summary": "Get Airline",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: AIRLINE:READ",
    "operationId": "ine",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "AIRLINE:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Airline"
    ],
    "summary": "Update Airline",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: AIRLINE:UPDATE",
    "operationId": "irline",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "AIRLINE:UPDATE"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Airline"
    ],
    "summary": "Delete Airline",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: AIRLINE:DELETE",
    "operationId": "irline",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "AIRLINE:DELETE"
      ]
     }
    ]
   }
  },
  "/api/flight/v1/city": {
   "post": {
    "tags": [
     "City"
    ],
    "summary": "Create City",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: CITY:CREATE",
    "operationId": "e_city",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "CITY:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "City"
    ],
    "summary": "List Cities",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: CITY:READ",
    "operationId": "cities",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "CITY:READ"
      ]
     }
    ]
   }
  },
  "/api/flight/v1/city/{id}": {
   "get": {
    "tags": [
     "City"
    ],
    "summary": "Get City",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: CITY:READ",
    "operationId": "ity",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "CITY:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "City"
    ],
    "summary": "Update City",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: CITY:UPDATE",
    "operationId": "e_city",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "CITY:UPDATE"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "City"
    ],
    "summary": "Delete City",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: CITY:DELETE",
    "operationId": "e_city",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "CITY:DELETE"
      ]
     }
    ]
   }
  },
  "/api/flight/v1/airport": {
   "post": {
    "tags": [
     "Airport"
    ],
    "summary": "Create Airport",
    "description": "This Method is for creating an airport.",
    "operationId": "irport"
   },
   "get": {
    "tags": [
     "Airport"
    ],
    "summary": "List Airports",
    "description": "This Method is for listing airports.",
    "operationId": "ports"
   }
  },
  "/api/flight/v1/airport/{uuid}": {
   "get": {
    "tags": [
     "Airport"
    ],
    "summary": "Get Airport",
    "description": "This Method is for getting an airport.",
    "operationId": "ort"
   },
   "put": {
    "tags": [
     "Airport"
    ],
    "summary": "Update Airport",
    "description": "This Method is for updating an airport.",
    "operationId": "irport"
   },
   "delete": {
    "tags": [
     "Airport"
    ],
    "summary": "Delete Airport",
    "description": "This Method is for deleting an airport.",
    "operationId": "irport"
   }
  },
  "/api/flight/v1/autofill/{search}": {
   "get": {
    "tags": [
     "AutoFill"
    ],
    "summary": "Search Airport",
    "description": "This Method is for searching an airport.",
    "operationId": "rport"
   }
  }
 },
 "components": {
  "securitySchemes": {
   "OAuth2PasswordBearer": {
    "type": "oauth2",
    "flows": {
     "password": {
      "scopes": {},
      "tokenUrl": "https://account.owj.app/api/account/v1/auth/oauth2"
     }
    }
   }
  }
 }
}